
###
GET http://127.0.0.1:5000/getAppJWT HTTP/1.1

# https://api.storekit-sandbox.itunes.apple.com/inApps/v1/lookup/
### 查询用户订单的收据
GET https://api.storekit-sandbox.itunes.apple.com/inApps/v1/lookup/2000000027145897
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjhETFcyQU0yNUoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI2OWE2ZGU5Ni03MDBjLTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEiLCJpYXQiOjE2ODM4NzkzNzEsImV4cCI6MTY4Mzg4Mjk3MSwiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIiwibm9uY2UiOiJkMmIzOWUxMy1hYjM5LTRmZmQtYmE2Yi1kNTdiMGI4NjBmN2YiLCJiaWQiOiJjb20ubGVvemhvdS5Ub01lbW8ifQ.8B9jAJE1oTIwswLEPJuStfgNZ1G9eenAB_0UVxtBZHO9s4wtRM4NLzTfwyRJKYthKb8KvwHzijsp2hbj1AnRdA

# curl -H 'Accept: application/json' -H "Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjhETFcyQU0yNUoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI2OWE2ZGU5Ni03MDBjLTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEiLCJpYXQiOjE2ODM4NzkzNzEsImV4cCI6MTY4Mzg4Mjk3MSwiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIiwibm9uY2UiOiJkMmIzOWUxMy1hYjM5LTRmZmQtYmE2Yi1kNTdiMGI4NjBmN2YiLCJiaWQiOiJjb20ubGVvemhvdS5Ub01lbW8ifQ.8B9jAJE1oTIwswLEPJuStfgNZ1G9eenAB_0UVxtBZHO9s4wtRM4NLzTfwyRJKYthKb8KvwHzijsp2hbj1AnRdA" https://api.storekit-sandbox.itunes.apple.com/inApps/v1/lookup/2000000329169549
# curl -H 'Accept: application/json' -H "Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjhETFcyQU0yNUoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI2OWE2ZGU5Ni03MDBjLTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEiLCJpYXQiOjE2ODM4NzkzNzEsImV4cCI6MTY4Mzg4Mjk3MSwiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIiwibm9uY2UiOiJkMmIzOWUxMy1hYjM5LTRmZmQtYmE2Yi1kNTdiMGI4NjBmN2YiLCJiaWQiOiJjb20ubGVvemhvdS5Ub01lbW8ifQ.8B9jAJE1oTIwswLEPJuStfgNZ1G9eenAB_0UVxtBZHO9s4wtRM4NLzTfwyRJKYthKb8KvwHzijsp2hbj1AnRdA" https://api.storekit-sandbox.itunes.apple.com/inApps/v1/history/2000000329169549
### 历史单据
GET https://api.storekit-sandbox.itunes.apple.com/inApps/v1/history/2000000329169549
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjhETFcyQU0yNUoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI2OWE2ZGU5Ni03MDBjLTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEiLCJpYXQiOjE2ODM4NzkzNzEsImV4cCI6MTY4Mzg4Mjk3MSwiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIiwibm9uY2UiOiJkMmIzOWUxMy1hYjM5LTRmZmQtYmE2Yi1kNTdiMGI4NjBmN2YiLCJiaWQiOiJjb20ubGVvemhvdS5Ub01lbW8ifQ.8B9jAJE1oTIwswLEPJuStfgNZ1G9eenAB_0UVxtBZHO9s4wtRM4NLzTfwyRJKYthKb8KvwHzijsp2hbj1AnRdA

### 退款
GET https://api.storekit-sandbox.itunes.apple.com/inApps/v1/refund/lookup/2000000329169549
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjhETFcyQU0yNUoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI2OWE2ZGU5Ni03MDBjLTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEiLCJpYXQiOjE2ODM4NzkzNzEsImV4cCI6MTY4Mzg4Mjk3MSwiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIiwibm9uY2UiOiJkMmIzOWUxMy1hYjM5LTRmZmQtYmE2Yi1kNTdiMGI4NjBmN2YiLCJiaWQiOiJjb20ubGVvemhvdS5Ub01lbW8ifQ.8B9jAJE1oTIwswLEPJuStfgNZ1G9eenAB_0UVxtBZHO9s4wtRM4NLzTfwyRJKYthKb8KvwHzijsp2hbj1AnRdA

### 用户订阅项目状态
GET https://api.storekit-sandbox.itunes.apple.com/inApps/v1/subscriptions/2000000329169549
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6IjhETFcyQU0yNUoiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI2OWE2ZGU5Ni03MDBjLTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEiLCJpYXQiOjE2ODM4NzkzNzEsImV4cCI6MTY4Mzg4Mjk3MSwiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIiwibm9uY2UiOiJkMmIzOWUxMy1hYjM5LTRmZmQtYmE2Yi1kNTdiMGI4NjBmN2YiLCJiaWQiOiJjb20ubGVvemhvdS5Ub01lbW8ifQ.8B9jAJE1oTIwswLEPJuStfgNZ1G9eenAB_0UVxtBZHO9s4wtRM4NLzTfwyRJKYthKb8KvwHzijsp2hbj1AnRdA
