
### root request
GET http://127.0.0.1:5000/ HTTP/1.1

### generate token
POST http://127.0.0.1:5000/token/generate HTTP/1.1
content-type: application/json

{
    "uniqueUserId":"80CDB97C-73F4-44B7-B122-1C01685E0F20",
    "licenseKey":"E4622E5A23A746FF9EB5F9FFE0C51DD6"
}

### refresh token
POST http://127.0.0.1:5000/token/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NDQ5OTY4MiwianRpIjoiZTFjN2Y4MDMtYmU2MC00M2JmLTllOTYtOTk2ZWI1ZjQ2MTUxIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiI4MENEQjk3Qy03M0Y0LTQ0QjctQjEyMi0xQzAxNjg1RTBGMjAiLCJuYmYiOjE2ODQ0OTk2ODIsImV4cCI6MTY4NzA5MTY4Mn0.WGY0Hcs7Og-C3vgWcXtnp6Bnpy38IV0Eo5eBvoiZWC8

### test jwt token
GET http://127.0.0.1:5000/token/test HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4NTAxNjMxNiwianRpIjoiYjI5ZWI2ODYtNDY1Zi00NWVlLWE5MzgtYTdiYzhhYmE2M2IyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjgwQ0RCOTdDLTczRjQtNDRCNy1CMTIyLTFDMDE2ODVFMEYyMCIsIm5iZiI6MTY4NTAxNjMxNiwiZXhwIjoxNjg1MTAyNzE2fQ.gQpN9YLNlhTq-6oR4YSk1j5jxdmid1N_g0IV05x2GIs



