
### root request
GET http://127.0.0.1:5000/ HTTP/1.1

### open ai completion
POST http://127.0.0.1:5000/completions HTTP/1.1
content-type: application/json

{
    "message": "tell me what is embedding",
    "channelSubject": "you are a special AI assistant, you can answer me any question."
}

### open ai completion
POST http://127.0.0.1:5000/chat HTTP/1.1
content-type: application/json

{
    "messages": [{"role":"user", "content":"tell me what is embedding"}],
    "channelSubject": "you are a special AI assistant, you can answer me any question."
}

### handle user
POST http://127.0.0.1:5000/handle/user HTTP/1.1
content-type: application/json

{
    "uniqueUserId": "uniqueUserId",
    "iCloudRecordUserId": ""
}

### jwt protected
GET http://127.0.0.1:5000/protected HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4MzYyMzE4OSwianRpIjoiOTlkNmJiZDMtYjYxMC00MDRjLTkwMjctMjQyMWE0ZTgxNWNlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVuaXF1ZVVzZXJJZCIsIm5iZiI6MTY4MzYyMzE4OSwiZXhwIjoxNjgzNzA5NTg5fQ.5sijtTuO-XmwuNWPgQb8a6N-JaSvT3ymQ80RgmNgTAQ

### 订阅状态

POST http://127.0.0.1:5000/sync/apple/transaction HTTP/1.1
content-type: application/json

{
  "bundleId" : "com.leozhou.ToMemo",
  "deviceVerification" : "",
  "deviceVerificationNonce" : "02472eea-9edb-4d46-b57c-358e4cc1576e",
  "environment" : "Sandbox",
  "expiresDate" : 1683816843000,
  "inAppOwnershipType" : "PURCHASED",
  "offerType" : 1,
  "originalPurchaseDate" : 1683816670000,
  "originalTransactionId" : "2000000329169549",
  "productId" : "com.leozhou.tomemo.subscribe.advanced.yearly",
  "purchaseDate" : 1683816663000,
  "quantity" : 1,
  "signedDate" : 1683816676462,
  "subscriptionGroupIdentifier" : "21080011",
  "transactionId" : "2000000329169549",
  "type" : "Auto-Renewable Subscription",
  "webOrderLineItemId" : "2000000027145897"
}